Fix/FE: Jenkinsfile 수정

diff --git a/Front/Jenkinsfile b/Front/Jenkinsfile
--- a/Front/Jenkinsfile
+++ b/Front/Jenkinsfile
@@ -32,28 +32,21 @@ pipeline {
                 sh "docker container ls -a -q -f name=${env.CONTAINER_NAME_FE} | xargs --no-run-if-empty docker rm"
             }
         }
-
-        // 이미지 삭제
-        stage("Docker Image Cleaning") {
-            steps{
-                sh "docker images ${env.IMAGE_NAME_FE} -q | xargs -r docker rmi -f"
-            }
-        }
         
         // 도커 이미지 빌드
         stage("Docker Image Build") {
             steps {
-                script {  // 'script' 블록 추가
-                    try {
+                // script {  // 'script' 블록 추가
+                    // try {
                         dir("${env.PROJECT_DIR_FE}") {
-                            sh "docker build --no-cache -t ${env.IMAGE_NAME_FE}:latest -t ${env.IMAGE_NAME_FE}:${BUILD_NUMBER} ."
+                            sh "docker build --no-cache -t ${env.IMAGE_NAME_FE}:${BUILD_NUMBER} ."
                         }
-                    } catch (Exception e) {
-                        // 빌드를 중지하고 오류 상태로 설정합니다.
-                        echo "Docker build failed: ${e.getMessage()}"
-                        error "Stopping build due to errors"
-                    }
-                }
+                    // } catch (Exception e) {
+                    //     // 빌드를 중지하고 오류 상태로 설정합니다.
+                    //     echo "Docker build failed: ${e.getMessage()}"
+                    //     error "Stopping build due to errors"
+                    // }
+                // }
             }
         }
 
@@ -67,30 +60,30 @@ pipeline {
             }
         }
 
-        // 롤백 스테이지 (선택적)
-        stage('Rollback on Failure') {
-            when {
-                // 이전 단계들 중에서 실패한 경우에만 이 스테이지 실행
-                expression { currentBuild.currentResult == 'FAILURE' }
-            }
-            steps {
-                script {
-                    // 마지막 성공한 빌드에서 artifact 다운로드
-                    def lastSuccessfulBuild = currentBuild.rawBuild.getPreviousSuccessfulBuild()
+        // // 롤백 스테이지 (선택적)
+        // stage('Rollback on Failure') {
+        //     when {
+        //         // 이전 단계들 중에서 실패한 경우에만 이 스테이지 실행
+        //         expression { currentBuild.currentResult == 'FAILURE' }
+        //     }
+        //     steps {
+        //         script {
+        //             // 마지막 성공한 빌드에서 artifact 다운로드
+        //             def lastSuccessfulBuild = currentBuild.rawBuild.getPreviousSuccessfulBuild()
 
-                    if (lastSuccessfulBuild != null) {
-                        def artifact = lastSuccessfulBuild.getArtifactManager().root().child('successful_tag.txt')
-                        def tagInfo = artifact.readToString()  // 파일 내용 읽기
+        //             if (lastSuccessfulBuild != null) {
+        //                 def artifact = lastSuccessfulBuild.getArtifactManager().root().child('successful_tag.txt')
+        //                 def tagInfo = artifact.readToString()  // 파일 내용 읽기
 
-                        echo "Rolling back to previous stable build: ${tagInfo}..."
-                        // 태그 정보를 사용하여 이전 버전의 이미지로 컨테이너 시작
-                        sh "docker run -d -p 3001:3000 --name ${env.CONTAINER_NAME_FE}_rollback ${tagInfo}"
-                    } else {
-                        echo "No successful build to rollback to!"
-                    }
-                }
-            }
-        }
+        //                 echo "Rolling back to previous stable build: ${tagInfo}..."
+        //                 // 태그 정보를 사용하여 이전 버전의 이미지로 컨테이너 시작
+        //                 sh "docker run -d -p 3001:3000 --name ${env.CONTAINER_NAME_FE}_rollback ${tagInfo}"
+        //             } else {
+        //                 echo "No successful build to rollback to!"
+        //             }
+        //         }
+        //     }
+        // }
     }
 
     post {
@@ -104,11 +97,40 @@ pipeline {
                 // 'successful_tag.txt'라는 파일에 성공한 빌드의 태그 정보를 저장합니다.
                 writeFile file: 'successful_tag.txt', text: "${env.IMAGE_NAME_FE}:${BUILD_NUMBER}"
                 archiveArtifacts artifacts: 'successful_tag.txt'  // 이 파일을 Jenkins artifact로 보관합니다.
+            
+                // 최근 성공한 이미지 태그 목록을 유지하기 위한 로직
+                def recentSuccessfulTags = []  // 성공한 태그들을 저장할 리스트
+                def maxImagesToKeep = 5  // 유지할 이미지 수
+
+                // 이전 성공 빌드들로부터 태그 정보를 가져옵니다.
+                def build = currentBuild
+                while (build != null && recentSuccessfulTags.size() < maxImagesToKeep) {
+                    def artifact = build.getArtifactManager().root().child('successful_tag.txt')
+                    if (artifact.exists()) {
+                        def tagInfo = artifact.readToString()
+                        recentSuccessfulTags.add(tagInfo)
+                    }
+                    build = build.getPreviousSuccessfulBuild()
+                }
+
+                // 전체 이미지 리스트를 가져옵니다.
+                def allImages = sh(script: "docker images ${env.IMAGE_NAME_FE} --format '{{.Repository}}:{{.Tag}}' ", returnStdout: true).trim().split('\n')
+
+                // 유지할 이미지 목록에서 제외된 이미지들을 삭제합니다.
+                for (image in allImages) {
+                    if (!recentSuccessfulTags.contains(image)) {
+                        sh "docker rmi ${image} || true"  // 삭제 중 오류가 발생해도 계속 진행합니다.
+                    }
+                }
             }
         }
         failure {
             // 빌드가 실패한 경우 롤백 메커니즘 실행
             script {
+                // 현재 빌드에서 생성된 이미지를 삭제합니다. 이 명령은 빌드 실패 시에만 실행됩니다.
+                sh "docker rmi ${env.IMAGE_NAME_FE}:${BUILD_NUMBER} || true"  // 실패해도 빌드 프로세스를 계속합니다.
+
+
                 // 마지막 성공한 빌드에서 artifact 다운로드
                 def lastSuccessfulBuild = currentBuild.rawBuild.getPreviousSuccessfulBuild()
                 
